version: 0.2
phases:
  install:
    commands:
      - printenv
      - |
        export DEBIAN_FRONTEND=noninteractive
        apt-get update
        php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
        php composer-setup.php ;
        php -r "unlink('composer-setup.php');" ;
        mv composer.phar /usr/local/bin/composer
  pre_build:
      commands:
        - cp .env.example .env.prod
        - sed -i "s/DB_HOST=.*/DB_HOST=$DB_HOST/g" .env.prod
        - sed -i "s/DB_PORT=.*/DB_PORT=$DB_PORT/g" .env.prod
        - sed -i "s/DB_DATABASE=.*/DB_DATABASE=$DB_DATABASE/g" .env.prod
        - sed -i "s/DB_USERNAME=.*/DB_USERNAME=$DB_USERNAME/g" .env.prod
        - sed -i "s/DB_PASSWORD=.*/DB_PASSWORD=$DB_PASSWORD/g" .env.prod
  build:
    commands:
      - composer install
      - npm install
      - npm run dev
artifacts:
  files:
    - '**/*'
