version: 0.2
phases:
  install:
    commands:
      - |
        export DEBIAN_FRONTEND=noninteractive
        apt-get update
        php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
        php composer-setup.php ;
        php -r "unlink('composer-setup.php');" ;
        mv composer.phar /usr/local/bin/composer
  build:
    commands:
      - composer install
      - npm install
      - npm run build
