version: 0.2
phases:
  install:
    commands:
      - printenv
      - |
        export DEBIAN_FRONTEND=noninteractive
        apt-get update
        php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
        php composer-setup.php ;
        php -r "unlink('composer-setup.php');" ;
        mv composer.phar /usr/local/bin/composer
  pre_build:
      commands:
        - cp .env.example .env.prod
        - echo $DB_HOST
        - echo $DB_DATABASE
        - echo $DB_USERNAME
        - echo $DB_PASSWORD
  build:
    commands:
      - composer install
      - npm install
      - npm run dev
artifacts:
  files:
    - '**/*'
