version: 0.2
phases:
  install:
    commands:
      - |
        export DEBIAN_FRONTEND=noninteractive
        apt-get update
        php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
        php composer-setup.php ;
        php -r "unlink('composer-setup.php');" ;
        mv composer.phar /usr/local/bin/composer
  build:
    commands:
      - chmod -R 777 storage
      - composer install
      - npm install
      - npm run dev
      - cp .env.example .env
      - php artisan key:generate
      - sed -i 's/DB_HOST=.*/DB_HOST=${DB_HOST}/' .env
      - sed -i 's/DB_PORT=.*/DB_PORT=${DB_PORT}/' .env
      - sed -i 's/DB_DATABASE=.*/DB_DATABASE=${DB_DATABASE}/' .env
      - sed -i 's/DB_USERNAME=.*/DB_USERNAME=${DB_USERNAME}/' .env
      - sed -i 's/DB_PASSWORD=.*/DB_PASSWORD=${DB_PASSWORD}/' .env
artifacts:
  files:
    - '**/*'
