version: 0.2
phases:
  install:
    runtime-versions:
      - php: 8.1
      - nodejs: least
    commands:
      - apt-get update
      - php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
      - php composer-setup.php
      - php -r "unlink('composer-setup.php');"
      - mv composer.phar /usr/local/bin/composer
  build:
    commands:
      - composer install
      - npm install
      - npm run build
