@startuml

!define Table class
!define PK <<PK>>
!define FK <<FK>>

skinparam linetype ortho

Table global_settings {
  + id : int PK
  global_app_name : string
  logo : string
  favicon : string
  login_background : string
  header_color : string
  sidebar_logo_style : string
  locale : string
  date_format : string
  timezone : string
  time_format : string
  moment_format : string
}

Table language_settings {
  + id : int PK
  language_code : string
  language_name : string
  flag_code : string
  enabled : char
}

Table clients {
  + id : int PK
  name : string
  app_name : string
  email : string
  phone : string
  logo : string
  login_background : string
  address : string
  website : string
  timezone : string
  date_format : string
  date_picker_format : string
  moment_format : string
  locale : string
  latitude : decimal
  longitude : decimal
}

Table location_type {
  + id : int PK
  code : string
  description : string
}

Table locations {
  + id : int PK
  code : string
  description : string
  client_id : int
  location_type_id : int
  latitude : decimal
  longitude : decimal
}

Table users {
  + id : int PK
  client_id : int
  name : string
  email : string
  type : tinyint
  password : string
  avatar : string
  mobile : string
  gender : tinyint
  locale : string
  active : char
  login : char
  onesignal_player_id : text
  remember_token : string
}

Table lockers {
  + id : int PK
  code : string
  description : string
  status : tinyint
  location_id : int
}

Table locker_slots {
  + id : int PK
  locker_id : int
  status : tinyint
  x_coor : int
  y_coor : int
}

Table licenses {
  + id : int PK
  code : string
  client_id : int
  locker_id : int
  active_date : date_time
  expired_date : date_time
}

Table bookings {
  + id : int PK
  client_id : int
  locker_slot_id : int
  owner_id : int
  status : tinyint
  start_time : date_time
  end_time : date_time
}

clients -- locations : <<FK>>
clients -- users : <<FK>>
locations -- location_type : <<FK>>
locations -- lockers : <<FK>>
lockers -- locker_slots : <<FK>>
licenses -- lockers : <<FK>>
licenses -- clients : <<FK>>
bookings -- clients : <<FK>>
bookings -- locker_slots : <<FK>>
bookings -- users : <<FK>>

@enduml
