#!/bin/bash
yum install -y httpd
sudo dnf install php8.2 -y

cp /var/www/html/.env.example /var/www/html/.env
cp /var/www/html/scripts/utelocker.conf /etc/httpd/conf.d/

php /var/www/html/artisan key:generate
